### ISSUE TITLE
this should be removed, this was mid-implementation and i left it in

### ISSUE THREAD

**Issue by cmr624** [flower-water-games/mech-preprod#16]
https://github.com/flower-water-games/mech-preprod/blob/4861167f26df7b65a9858f2139c9db24db5e68ac/scripts/enemy/enemy.gd#L52

**Comment by cmr624** [comment]
there's some code throughout that's remnants of a previous implementation of the bomb enemy i forgot to take out. its non invasive (lol) but should be removed.

**Comment by gloriousclover** [comment]
Will be removed as part of next push
