### ISSUE TITLE
should the game manager be refactored for the submission

### ISSUE THREAD

**Issue by cmr624** [flower-water-games/mech-preprod#21]
https://github.com/flower-water-games/mech-preprod/blob/2d93622095c1a6d4a2a20e89410d640445e3cf6c/documentation/README.md?plain=1#L20

the game manager does more than just this, but it is true that currently spawning waves the bulk of the code. so note 1 is for me to just note this in the documentation

but question is also, does the team want this be separated out into a wave manager to handle stateful data and to keep the game manager focused on its unique access to all game data.

however, if we're not really adding any more functionality, this script could be good enough.

**Comment by gloriousclover** [comment]
It makes sense to me that the game manager handles all the interactions between the scene elements. Will probably refactor what I think will make things easier regardless, but at first glance today looks good to me

**Comment by cmr624** [comment]
fantastic, thanks @gloriousclover
